l_korean:
 message_settings_tab_settings: "설정"
 message_settings_tab_log: "메시지 로그"
 MESSAGE_SETTINGS_WINDOW_NAME: "메시지 설정"
 MESSAGE_SETTINGS_WINDOW_SHORTCUT_TT: "#I 클릭하여 메시지 설정 보기#!"
 MESSAGE_SETTINGS_WINDOW_TT: "#T $MESSAGE_SETTINGS_WINDOW_NAME$#!\n필터 그룹으로 메시지의 빈도와 표시 여부를 편집합니다."
 MESSAGE_SETTINGS_WINDOW_RESET: "기본값으로 초기화"
 MESSAGE_SETTINGS_WINDOW_RESET_TT: "#T 메시지 설정 초기화#!\n#I 클릭하여 현재 변경 사항을 기본 설정으로 초기화합니다.#!"
 MESSAGE_SETTINGS_WINDOW_APPLY: "변경 사항 적용"
 MESSAGE_SETTINGS_WINDOW_APPLY_TT: "#T $MESSAGE_SETTINGS_WINDOW_APPLY$#!\n#I 클릭하여 메시지 설정 창을 닫고 현재 변경 사항을 저장합니다.#!"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_FEED: "@check_icon! 피드"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_TOAST: "@alert_icon! 알림"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_POPUP: "@opinion_icon! 팝업"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_HIDDEN: "@cross_icon! 없음"
 MESSAGE_SETTINGS_WINDOW_GROUP_HEADER: "$NAME$ #weak ($SIZE$)#!"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE: "필터 그룹"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE_TT: "메시지 이름 필터 그룹"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE: "외형"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE_TT: "해당 필터 그룹 표시 방법"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE: "일시 정지"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE_TT: "해당 필터에 속한 메시지가 나타났을 때 게임 일시 정지 여부를 설정합니다."
 MESSAGE_SETTINGS_WINDOW_TOGGLE_AUTO_PAUSE_TT: "#T 자동 일시 정지 전환#!\n#I 해당 필터에 속한 메시지가 나타났을 때 게임을 일시 정지하도록 합니다.#!"
 MESSAGE_SETTINGS_WINDOW_CLOSE_POPUP: "#T 메시지 닫기#!\n#I 클릭하여 현재 메시지를 닫고 대기열에 있는 다음 메시지를 표시합니다.#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TITLE: "사용자 지정 메시지"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TT: "#T 메시지 사용자 지정#!\n#I 클릭하여 자신에게 보내는 사용자 지정 메시지를 작성하고 수신 시기를 선택합니다#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DATE: "도착 일자: [DATE.GetString|V]"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_TITLE: "제목:"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_DESC: "내용:"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD: "취소"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD_TT: "#T 메시지 취소#!\n#I 클릭하여 현재 메시지를 취소합니다#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND: "보내기"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND_TT: "#T 보내기#!\n#I 클릭하여 현재 메시지를 보냅니다#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DAY: "일"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_MONTH: "월"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_YEAR: "년"
