l_french:
 message_settings_tab_settings: "Paramètres"
 message_settings_tab_log: "Journal des messages"
 MESSAGE_SETTINGS_WINDOW_NAME: "Paramètres des messages"
 MESSAGE_SETTINGS_WINDOW_SHORTCUT_TT: "#I Cliquez pour ouvrir les paramètres des messages#!"
 MESSAGE_SETTINGS_WINDOW_TT: "#T $MESSAGE_SETTINGS_WINDOW_NAME$#!\nModifiez la fréquence et la visibilité des messages par groupes filtrés."
 MESSAGE_SETTINGS_WINDOW_RESET: "Réinitialiser les paramètres"
 MESSAGE_SETTINGS_WINDOW_RESET_TT: "#T Réinitialiser les paramètres des messages#!\n#I Cliquez pour revenir aux paramètres par défaut#!"
 MESSAGE_SETTINGS_WINDOW_APPLY: "Appliquer les modifications"
 MESSAGE_SETTINGS_WINDOW_APPLY_TT: "#T $MESSAGE_SETTINGS_WINDOW_APPLY$#!\n#I Cliquez pour fermer la fenêtre Paramètres des messages et enregistrer les modifications actuelles#!"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_FEED: "@check_icon! Flux"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_TOAST: "@alert_icon! Toast"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_POPUP: "@opinion_icon! Popup"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_HIDDEN: "@cross_icon! Jamais"
 MESSAGE_SETTINGS_WINDOW_GROUP_HEADER: "$NAME$ #weak ($SIZE$)#!"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE: "Groupe de filtres"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE_TT: "Nom du groupe de filtres de messages"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE: "Apparence"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE_TT: "Comment afficher les messages de ce groupe de filtres"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE: "Mettre en pause"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE_TT: "Si le jeu doit se mettre en pause lorsque les messages de ce filtre apparaissent"
 MESSAGE_SETTINGS_WINDOW_TOGGLE_AUTO_PAUSE_TT: "#T Activer la pause automatique#!\n#I Mettre le jeu en pause lorsque les messages de ce filtre apparaissent#!"
 MESSAGE_SETTINGS_WINDOW_CLOSE_POPUP: "#T Ignorer le message#!\n#I Cliquer pour ignorer le message actuel et afficher le message suivant dans la file d’attente#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TITLE: "Message personnalisé"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TT: "#T Message personnalisé#!\n#I Cliquez pour vous écrire un message personnalisé et choisissez quand vous souhaitez le recevoir#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DATE: "Date d’arrivée : [DATE.GetString|V]"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_TITLE: "Titre :"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_DESC: "Description :"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD: "Supprimer"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD_TT: "#T Supprimer le message#!\n#I Cliquez pour supprimer le message actuel#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND: "Envoyer"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND_TT: "#T Envoyer#!\n#I Cliquez pour envoyer le message actuel#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DAY: "Jour"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_MONTH: "Mois"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_YEAR: "An"
