l_spanish:
 message_settings_tab_settings: "Ajustes"
 message_settings_tab_log: "Registro de mensajes"
 MESSAGE_SETTINGS_WINDOW_NAME: "Configuración de mensajes"
 MESSAGE_SETTINGS_WINDOW_SHORTCUT_TT: "#I Haz clic para abrir la configuración de mensajes#!"
 MESSAGE_SETTINGS_WINDOW_TT: "#T $MESSAGE_SETTINGS_WINDOW_NAME$#!\nEditar la frecuencia y visibilidad de los mensajes filtradas por grupos."
 MESSAGE_SETTINGS_WINDOW_RESET: "Predeterminada"
 MESSAGE_SETTINGS_WINDOW_RESET_TT: "#T Reiniciar la configuración de mensajes#!\n#I Haz clic para reiniciar a la configuración predeterminada#!"
 MESSAGE_SETTINGS_WINDOW_APPLY: "Aplicar cambios"
 MESSAGE_SETTINGS_WINDOW_APPLY_TT: "#T $MESSAGE_SETTINGS_WINDOW_APPLY$#!\n#I Haz clic para cerrar la pantalla de configuración de mensajes y guardar los cambios#!"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_FEED: "@check_icon! Noticias"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_TOAST: "@alert_icon! Notificaciones"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_POPUP: "@opinion_icon! Ventana emergente"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_HIDDEN: "@cross_icon! Nunca"
 MESSAGE_SETTINGS_WINDOW_GROUP_HEADER: "$NAME$ #weak ($SIZE$)#!"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE: "Grupo de filtrado"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE_TT: "Nombre del grupo de filtrado de mensajes"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE: "Aspecto"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE_TT: "Cómo aparecerán los mensajes de este grupo de filtrado"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE: "Pausa"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE_TT: "Indica si la partida debe entrar en pausa cuando aparezcan mensajes de este filtro"
 MESSAGE_SETTINGS_WINDOW_TOGGLE_AUTO_PAUSE_TT: "#T Activar autopausa#!\n#I Activa esta opción para pausar la partida cuando aparezcan mensajes de este filtro#!"
 MESSAGE_SETTINGS_WINDOW_CLOSE_POPUP: "#T Descartar mensaje#!\n#I Haz clic para descartar el mensaje actual y mostrar el siguiente de la cola#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TITLE: "Mensaje personalizado"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TT: "#T Mensaje personalizado#!\n#I Haz clic para escribirte un mensaje y seleccionar cuándo quieres recibirlo#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DATE: "Fecha de llegada: [DATE.GetString|V]"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_TITLE: "Título:"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_DESC: "Descripción:"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD: "Descartar"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD_TT: "#T Descartar mensaje#!\n#I Haz clic para descartar el mensaje actual#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND: "Enviar"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND_TT: "#T Enviar#!\n#I Haz clic para enviar el mensaje actual#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DAY: "Día"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_MONTH: "Mes"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_YEAR: "Año"
