l_russian:
 MOD_ARTIFACT_DECAY_REDUCTION_ADD: "Снижение разрушения [Concept('artifact', 'артефакта')|E]"
 MOD_ARTIFACT_DECAY_REDUCTION_MULT: "$MOD_ARTIFACT_DECAY_REDUCTION_ADD$"
 artifact_history_created_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_created_desc: "Создатель: [SelectLocalization( HISTORY_ENTRY.HasActor, HISTORY_ENTRY.GetActor.GetNameNoTooltip, 'UNKNOWN_BENEFACTOR' )]\nСоздано для: [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]\nМесто создания: [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]"
 artifact_history_stolen_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_stolen_desc: "Похищено персонажем [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 artifact_history_created_before_history_title: "Создание неизвестно"
 artifact_history_created_before_history_desc: "Подробности создания этого артефакта неизвестны"
 artifact_history_given_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_given_desc: "Подарено персонажу [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 artifact_history_inherited_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_inherited_desc: "Унаследовано персонажем [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 artifact_history_conquest_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_conquest_desc: "Захвачено персонажем [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] в войне против персонажа [HISTORY_ENTRY.GetActor.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 artifact_history_taken_in_siege_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_taken_in_siege_desc: "Захвачено персонажем [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] после осады владения [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]"
 artifact_history_reforged_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_reforged_desc: "Объединено персонажем [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] из провинции [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]"
 artifact_history_discovered_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_discovered_desc: "Открыто персонажем [HISTORY_ENTRY.GetActor.GetTitledFirstNameNicknamedNoTooltipRegnal] по поручению персонажа [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] в провинции [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]"
 artifact_history_claimed_by_house_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_claimed_by_house_desc: "Оспаривается [Concept( 'house', 'домом' )|E] [HISTORY_ENTRY.GetActor.GetHouse.GetNameNoTooltip]"
 artifact_history_won_in_duel_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_won_in_duel_desc: "Выиграно в поединке против персонажа [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 artifact_history_taken_in_battle_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_taken_in_battle_desc: "Захвачено персонажем [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] во время сражения в провинции [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]"
 artifact_history_prize_created_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_prize_created_desc: "Персонаж [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] предложил этот артефакт в качестве [Concept( 'prize', 'приза' )|E] на таком мероприятии, как [GetActivityType( 'activity_tournament' ).GetName]"
 artifact_history_prize_awarded_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_prize_awarded_desc: "[HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] [Select_CString(HISTORY_ENTRY.GetRecipient.IsFemale, 'получила', 'получил' )] этот артефакт в качестве [Concept( 'prize', 'приза' )|E] за победу в [Concept( 'contest', 'состязании' )|E]"
 artifact_history_creator_discovered_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_creator_discovered_desc: "Выяснилось, что этот артефакт [Select_CString(HISTORY_ENTRY.GetRecipient.IsFemale, 'создала', 'создал' )] [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 artifact_history_purchased_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_purchased_desc: "Приобретено персонажем [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 artifact_history_ransomed_title: "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_ransomed_desc: "Выкуплено персонажем [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 UNKNOWN_BENEFACTOR: "неизвестный благодетель"
 ARTIFACT_DURABILITY: "Прочность: $CURRENT|1$ / $MAX|1$"
 ARTIFACT_HISTORY: "История артефакта"
 crown: "Венец"
 helmet: "Головной убор"
 miscellaneous: "$trinket$"
 miscellaneous_when_not_court: "$trinket$"
 regalia: "Регалия"
 journal: "Журнал"
 weapon: "Оружие"
 primary_armament: "$weapon$"
 armor: "Доспех"
 trinket: "Украшение"
 trinket_1: "$trinket$"
 trinket_2: "$trinket$"
 trinket_3: "$trinket$"
 trinket_4: "$trinket$"
 #Names for the artifact that are placed in the slot
 artifact_slot_pedestal: "Предмет для пьедестала"
 artifact_slot_helmet: "Головной убор"
 artifact_slot_miscellaneous: "Украшение"
 artifact_miscellaneous_when_not_court: "$miscellaneous_when_not_court$"
 artifact_slot_armor: "Доспех"
 artifact_slot_sculpture: "Мебель"
 artifact_slot_primary_armament: "Оружие"
 artifact_slot_throne: "Трон"
 artifact_slot_wall_big: "Большой настенный орнамент"
 artifact_slot_regalia: "Регалии"
 artifact_slot_wall_small: "Малый настенный орнамент"
 artifact_slot_book: "Книга"
 artifact_slot_journal: "Журнал"
 artifact_crown: "Корона"
 artifact_helmet: "Головной убор"
 artifact_helmet_simple: "$artifact_helmet$"
 artifact_miscellaneous: "$trinket$"
 artifact_journal: "Журнал"
 artifact_journal_simple: "$artifact_journal$"
 artifact_regalia: "Регалии"
 artifact_regalia_simple: "$regalia$"
 artifact_armor: "Доспех"
 artifact_trinket: "Украшение"
 artifact_pedestal: "Предмет для пьедестала"
 artifact_wall_big: "Большой настенный орнамент"
 artifact_tapestry: "Гобелен"
 artifact_sculpture: "Мебель"
 artifact_scientific_apparatus: "Научный прибор"
 artifact_wall_small: "Малый настенный орнамент"
 artifact_animal_skull: "Череп животного"
 artifact_animal_hide: "Шкура животного"
 artifact_animal_hide_big: "Большая шкура животного"
 artifact_throne: "Трон"
 artifact_box: "Шкатулка "
 artifact_goblet: "Кубок "
 artifact_jug: "Кувшин"
 artifact_book: "Книга"
 artifact_panacea: "Панацея "
 artifact_elixir: "Эликсир"
 artifact_philosophers_stone: "Философский камень"
 #These keys all use $weapon$ because despite being unique types, they all go in the weapon slot
 artifact_sword: "меч"
 artifact_axe: "топор"
 artifact_spear: "копье"
 artifact_hammer: "молот"
 artifact_dagger: "кинжал"
 artifact_mace: "булава"
 #Same as the above, but for armor types
 artifact_armor_mail: "$armor$"
 artifact_armor_plate: "$armor$"
 artifact_armor_scale: "$armor$"
 artifact_armor_lamellar: "$armor$"
 artifact_armor_laminar: "$armor$"
 artifact_armor_brigandine: "$armor$"
 pedestal: "Пьедестал"
 wall_big: "Большой настенный орнамент"
 wall_small: "Малый настенный орнамент"
 sculpture: "Мебель"
 throne: "Трон"
 book: "Книга"
 wall_big_1: "$wall_big$"
 wall_big_2: "$wall_big$"
 wall_big_3: "$wall_big$"
 wall_small_1: "$wall_small$"
 wall_small_2: "$wall_small$"
 wall_small_3: "$wall_small$"
 sculpture_1: "$sculpture$"
 sculpture_2: "$sculpture$"
 lectern_1: "$book$"
 lectern_2: "$book$"
 lectern_3: "$book$"
 pedestal_1: "$pedestal$"
 pedestal_2: "$pedestal$"
 pedestal_3: "$pedestal$"
 pedestal_4: "$pedestal$"
 #rarity levels
 common: ""
 masterwork: "Мастерский"
 famed: "Знаменитый"
 illustrious: "Великолепный"
 #old rarity levels (unused?)
 legendary: "Легендарный"
 rare: "Редкий"
 REFORGE_ARTIFACT_TITLE: "Перековать артефакт"
 REFORGE: "Перековать"
 REFORGE_ARTIFACT: "#T $REFORGE_ARTIFACT_TITLE$#!"
 REPAIR_ARTIFACT_TITLE: "Починить артефакт"
 REPAIR: "Починить"
 REPAIR_ARTIFACT: "#T $REPAIR_ARTIFACT_TITLE$#!"
 EFFECTS_ON_ARTIFACT: "Эффекты на артефакте «[Artifact.GetName]»"
 CHARACTER_PAYS_REFORGE_COST: "[CHARACTER.GetNamePossessiveOrMy|U][Select_CString(CHARACTER.IsLocalPlayer, ' персонаж', '' )] заплатит $COST$, чтобы перековать артефакт «[ARTIFACT.GetName]»"
 CHARACTER_PAYS_REPAIR_COST: "[CHARACTER.GetNamePossessiveOrMy|U][Select_CString(CHARACTER.IsLocalPlayer, ' персонаж', '' )] заплатит $COST$, чтобы починить артефакт «[ARTIFACT.GetName]»"
 ARTIFACT_CHANGES_NAME: "Артефакт «[ARTIFACT.GetName]» теперь будет называться «$NEW_NAME$»"
 ARTIFACT_CHANGES_DESC: "Изменится описание артефакта «[ARTIFACT.GetName]»"
 ARTIFACT_CHANGES_VISUALS: "[ARTIFACT.GetName] внешне изменится"
 ARTIFACT_CHANGES_TYPE: "Артефакт «[ARTIFACT.GetName]» сменит тип на «$NEW_TYPE$»"
 ARTIFACT_CHANGES_RARITY: "Редкость артефакта «[ARTIFACT.GetName]» изменится на «$NEW_RARITY$»"
 ARTIFACT_CHANGES_MODIFIER: "Артефакт «[ARTIFACT.GetName]» предоставит следующие бонусы:\n$NEW_MODIFIER$"
 ARTIFACT_CHANGES_TEMPLATE: "Артефакт «[ARTIFACT.GetName]» станет $NEW_TEMPLATE$"
 ARTIFACT_CHANGES_DURABILITY: "Прочность артефакта «[ARTIFACT.GetName]» изменится на $NEW_DURABILITY$ / $MAX_DURABILITY$"
 ARTIFACT_FULLY_REPAIRED: "Артефакт «[ARTIFACT.GetName]» будет полностью восстановлен"
 NEW_ARTIFACT_TOOLTIP: "Это новый [Concept( 'artifact', 'артефакт' )|E]"
 ARTIFACT_RARITY_AND_TYPE: "[ARTIFACT.GetType] ([ARTIFACT.GetRarity] артефакт)"
 ARTIFACT_TYPE_ONLY: "[ARTIFACT.GetType]"
 ARTIFACT_RARITY_AND_SLOT_TYPE: "[ARTIFACT.GetSlotType] ([ARTIFACT.GetRarity] артефакт)"
 ARTIFACT_SLOT_TYPE_ONLY: "[ARTIFACT.GetSlotType]"
 INVENTORY_ARTIFACTS_SINGLE: "[inventory_artifact|E]"
 RENAME_ARTIFACT: "#T Переименовать артефакт#!"
 RENAME_ARTIFACT_TITLE: "Переименовать [ARTIFACT.GetNameNoTooltip]"
 RENAME_ARTIFACT_DESC: "Изменить название артефакта «[ARTIFACT.GetNameNoTooltip]»"
 RENAME_ARTIFACT_ACCEPT: "Принять"
 ARTIFACT_CURRENT_HOLDER: "Текущий владетель: [Artifact.GetOwner.GetName]"
 ARTIFACT_CREATOR: "Создатель: [Artifact.GetCreator.GetName]"
 DETAILS_TAB_HISTORY: "История"
 DETAILS_TAB_CLAIMS: "Претенденты"
 DETAILS_TAB_CLAIM_INTERACTIONS: "У вас есть претензия"
 DETAILS_TAB_NO_CLAIMANTS: "Ни у кого нет [Concept( 'artifact_claim', 'претензий' )|E] на этот [Concept( 'artifact', 'артефакт' )|E]"
 CHARACTER_HAS_NO_ARTIFACTS: "Нет [Concept( 'artifacts', 'артефактов' )|E]"
 CHARACTER_HAS_NO_CLAIMED_ARTIFACTS: "[artifact_claims|E] отсутствуют"
 ARTIFACT_DETAILS_TITLE: "Сведения об артефакте"
 ARTIFACT_DETAILS: "#T $ARTIFACT_DETAILS_TITLE$#!"
 ARTIFACT_SORTING_ALL_BUTTON: "Все"
 created: "Создан"
 reforged: "Перекован"
 given: "Отдан"
 stolen: "Украден"
 conquest: "Завоеван"
 created_before_history: "Неизвестного происхождения"
 inherited: "Унаследован"
 discovered: "Открыт"
 taken_in_siege: "В осаде"
 won_in_duel: "Выиграно в поединке"
 taken_in_battle: "Захвачено в сражении"
 tournament_prize_creation: "Приз турнира"
 tournament_prize_won: "Выиграно в состязании"
 CLAIMANT_ENTRY_HOUSE_HEAD: "Глава дома: [ClaimantEntry.GetHouse.GetHeadOfHouse.GetName]"
 ARTIFACT_YEARS_UNTIL_DECAY: "[Artifact.GetYearsUntilDecay] лет"
 ARTIFACT_DURABILITY_TOOLTIP: "#T Прочность#!\n#V $DURABILITY|1$ / $MAX_DURABILITY|1$#!\nПри нынешней скорости разрушения этот [Concept( 'artifact', 'артефакт' )|E] прослужит [ARTIFACT.GetYearsUntilDecay] лет, прежде чем у него закончится [Concept( 'durability', 'прочность' )|E] и он сломается."
 ARTIFACT_DURABILITY_NO_DECAY_TOOLTIP: "#T Прочность#!\n#V $DURABILITY|1$ / $MAX_DURABILITY|1$#!\nВ настоящий момент этот [Concept( 'artifact', 'артефакт' )|E] не разрушается и прослужит сколь угодно долго, если не начнет терять [Concept( 'durability', 'прочность' )|E]."
 DECAY_TOTAL: "Ежегодное разрушение"
 DECAY_BASE: "Базовое разрушение"
 CHARACTER_HAS_NO_VALID_SLOT: "@warning_icon! #X Нет ячеек для хранения артефакта «[ARTIFACT.GetName]»#!"
 SLOT_CANNOT_HOLD_ARTIFACT: "@warning_icon! #X $SLOT$ не подходит для хранения артефактов типа «$TYPE$»#!"
 EQUIP_ARTIFACT: "\n#I Щелкните, чтобы взять артефакт#!"
 UNEQUIP_QUICK_TT: "#T Снять#!"
 EQUIP_ARTIFACT_REPLACE: "\n#I Щелкните, чтобы заменить артефакт «$REPLACE_ARTIFACT$» на этот#!"
 SELECT_ARTIFACT: "Выбрать артефакт"
 ARTIFACT_ALREADY_EQUIPPED_IN_SLOT: "@warning_icon! #X Артефакт «[ARTIFACT.GetNameNoTooltip]» уже находится в этой ячейке#!"
 INVENTORY_SLOT_TT: "#T Ячейка «[InventorySlot.GetName]»\n#![SelectLocalization( InventoryView.IsSelectedSlot( InventorySlot.Self ), 'SELECT_ARTIFACT_FOR_SLOT', 'SELECT_INVENTORY_SLOT' )]"
 SELECT_INVENTORY_SLOT: "#I Щелкните, чтобы показать артефакт «[InventorySlot.GetName]»#!"
 SELECT_ARTIFACT_FOR_SLOT: "#I Щелкните, чтобы снять выделение#!"
 CHARACTER_CANNOT_DECLARE_WAR: "[Character.GetShortUINameNoTooltip|U] не может начать войну за этот [Concept( 'artifact', 'артефакт' )|E]"
 CHARACTER_CANNOT_DECLARE_WAR_SHORT: "Невозможно объявить войну"
 CHARACTER_CAN_DECLARE_WAR: "[Character.GetShortUINameNoTooltip|U] может начать войну за этот [Concept( 'artifact', 'артефакт' )|E]"
 #DECLARE_WAR_FOR_ARTIFACT_TOOLTIP: "#T Declare War for Artifact#!" #<DELETE THIS KEY>
 DUEL_FOR_ARTIFACT_TOOLTIP: "#T Поединок за артефакт#!"
 ARTIFACT_SORT_ORDER_TOOLTIP: "#T Изменить порядок сортировки артефактов#!"
 ARTIFACT_CLAIM_SORT_ORDER_TOOLTIP: "#T [artifact_claim|E]: изменить порядок сортировки#!"
 ARTIFACT_SORTING_TAB_TOOLTIP: "[artifacts|E]: [InventorySlotType.GetName]"
 ARTIFACT_SORTING_TAB_ALL_TOOLTIP: "Все [artifacts|El]"
 acquisition_date: "Дата получения"
 creation_date: "Дата создания"
 type: "Тип"
 rarity: "Редкость"
 name: "Название"
 durability: "Прочность"
 artifact_type: "Тип артефакта"
 claim_type: "Тип претензии"
 UNEQUIP_ARTIFACT: "\n#I Щелкните, чтобы убрать артефакт#!"
 ARTIFACT_EQUIPPED_TOOLTIP: "#T [artifact|E] взят#!"
 ARTIFACT_AT_MAX_DURABILITY: "@warning_icon! #X Артефакт «[ARTIFACT.GetNameNoTooltip]» уже обладает максимальной прочностью#!"
 IMMINENT_HOUSE_CLAIMANT: "[Artifact.GetOwner.GetHouse.GetName] #low ([Artifact.GetYearsUntilHouseClaim( Artifact.GetOwner.Self )] лет)#!"
 HOUSE_CLAIMS: "#help Претензии дома:#!"
 DECAY_ARTIFACT_EQUIPPED: "Взят"
 DECAY_ARTIFACT_DISPlAY: "Выставлен"
 DECAY_ARTIFACT_UNEQUIPPED: "В хранилище"
 DISPLAY_ARTIFACT: "#I \nЩелкните, чтобы выставить#!"
 PUT_COURT_ARTIFACT_ON_DISPLAY: "#I \nЩелкните, чтобы выставить здесь#!"
 REMOVE_COURT_ARTIFACT_FROM_DISPLAY: "#I \nЩелкните, чтобы убрать в хранилище#!"
 MOVE_COURT_ARTIFACT_TO_DISPLAY: "#I \nЩелкните, чтобы переместить сюда#!"
 COURT_ARTIFACT_ON_DISPLAY: "#T [court_artifact|E] показывается#!"
 ROYAL_COURT: "Монарший двор"
 ARTIFACT_STORAGE: "Придворные артефакты"
 ARTIFACT_CLAIMS: "Претензии на артефакты"
 NEW_ARTIFACT: "#V Новый#!"
 EQUIPPED_ARTIFACT: "[Select_CString( Artifact.IsCourtArtifact, 'Демонстрируется', 'Используется' )] [Inventory.GetEquippedSlotOfMaxSlotText( Artifact.Self )]"
 GIFT_EQUIPPED_ARTIFACT: "[Select_CString( Artifact.IsCourtArtifact, 'Выставляется', 'Используется' )]"
 CHARACTER_WITHOUT_ROYAL_COURT_COURT_ARTIFACT_TAB: "Так как [Character.GetShortUIName] не [Character.LocalPlayerString( 'имеете', 'имеет' )] [Concept( 'royal_court', 'монаршего двора' )|E], [Character.GetShortUIName] не [Character.LocalPlayerString( 'можете', 'может' )] выставить этот [court_artifact|El] на обозрение."
 ARTIFACT_TITLE_ASSOCIATION: "Унаследовано вместе с титулом «[Artifact.GetAssociatedTitle.GetNameWithUnderlying]»"
 EMPTY_INVENTORY_TOOLTIP: "@warning_icon! #X Нельзя посмотреть инвентарь: нет [Concept( 'artifacts', 'артефактов' )|E] или [Concept( 'artifact_claims', 'претензий на артефакты' )|E] для демонстрации#!"
 ARTIFACT_PERSONAL_CLAIM: "Личная претензия"
 ARTIFACT_HOUSE_CLAIM: "Претензия дома"
 REFORGE_ARTIFACT_COMPLETELY: "Перековать артефакт «[ARTIFACT.GetNameNoTooltip]» в тип «$NEW_TYPE$»"
 REFORGE_COST: "Стоимость перековки: $COST$"
 REPAIR_COST: "Стоимость починки : $COST$"
 CANNOT_REFORGE_WITHOUT_ANTIQUARIAN: "@warning_icon! #X Нельзя перековать [artifacts|El], так как у вас отсутствует $antiquarian_court_position$#!"
 ARTIFACT_FALLBACK_EFFECT: "#S Если вы не отвечаете требованиям:#!\n[Artifact.GetFallbackEffects]"
 ARTIFACT_EFFECT: "[SelectLocalization( Artifact.HasCanBenefit, 'ARTIFACT_EFFECT_HAS_CAN_BENEFIT', '' )][Artifact.GetModifierEffects]"
 ARTIFACT_EFFECT_HAS_CAN_BENEFIT: "#S Если вы отвечаете #TOOLTIP:ARTIFACT_EFFECT_REQUIREMENT_TT #L требованиям#!#!:#!\n"
 ARTIFACT_EFFECT_REQUIREMENT_TT: "[Artifact.GetCanBenefitPlayerDesc]"
 artifact_bowl: "Горшок"
 artifact_plate: "Тарелка"
 artifact_urn: "Урна"
 artifact_tun_barrel: "Винный чан"
